import io
import os

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app.core.config import settings
from app.models.user import User
from app.models.emergency_event import EmergencyEvent
from app.api.deps import get_current_user

router = APIRouter(prefix="/api/emergencies", tags=["reports"])

ROSE = colors.HexColor("#D96C8A")


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(
        letter[0] / 2, 0.4 * inch,
        "CONFIDENTIAL — Generated by SafeHer AI for authorized incident review only.",
    )
    canvas.drawRightString(letter[0] - 0.6 * inch, 0.4 * inch, f"Page {doc.page}")
    canvas.restoreState()


@router.get("/{emergency_id}/report")
async def generate_report(emergency_id: str, current_user: User = Depends(get_current_user)):
    event = await EmergencyEvent.get(emergency_id)
    if not event or (current_user.role != "admin" and event.owner_id != current_user.id):
        raise HTTPException(404, "Emergency not found.")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.7 * inch, bottomMargin=0.7 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleRose", parent=styles["Title"], textColor=ROSE)
    h2 = ParagraphStyle("H2Rose", parent=styles["Heading2"], textColor=ROSE)

    story = [
        Paragraph("SafeHer AI — Emergency Incident Report", title_style),
        Spacer(1, 12),
    ]

    info_rows = [
        ["Incident ID", event.id],
        ["Type", event.type.value if hasattr(event.type, "value") else str(event.type)],
        ["Status", event.status.value if hasattr(event.status, "value") else str(event.status)],
        ["Started At", event.started_at.strftime("%Y-%m-%d %H:%M:%S UTC") if event.started_at else "—"],
        ["Resolved At", event.resolved_at.strftime("%Y-%m-%d %H:%M:%S UTC") if event.resolved_at else "—"],
        ["Battery Level", f"{event.battery_level}%" if event.battery_level is not None else "—"],
        ["Contacts Notified", str(event.contacts_notified)],
    ]
    table = Table(info_rows, colWidths=[2 * inch, 4 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#FFF3F6")),
        ("TEXTCOLOR", (0, 0), (0, -1), ROSE),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#EEEEEE")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story += [table, Spacer(1, 16)]

    if event.latitude is not None and event.longitude is not None:
        maps_link = f"https://www.google.com/maps?q={event.latitude},{event.longitude}"
        story += [
            Paragraph("Location at Time of Incident", h2),
            Paragraph(f"Lat: {event.latitude}, Lng: {event.longitude}"),
            Paragraph(f'<link href="{maps_link}">{maps_link}</link>', styles["Normal"]),
            Spacer(1, 12),
        ]

    if event.location_history:
        story.append(Paragraph("Location History", h2))
        rows = [["Time", "Latitude", "Longitude", "Map"]]
        for point in event.location_history[:100]:
            link = f"https://www.google.com/maps?q={point['latitude']},{point['longitude']}"
            rows.append([
                point.get("timestamp", "—"), f"{point['latitude']:.5f}", f"{point['longitude']:.5f}",
                Paragraph(f'<link href="{link}">View</link>', styles["Normal"]),
            ])
        hist_table = Table(rows, colWidths=[2 * inch, 1.3 * inch, 1.3 * inch, 1 * inch])
        hist_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), ROSE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#EEEEEE")),
        ]))
        story += [hist_table, Spacer(1, 16)]

    if event.evidence_photos:
        story.append(Paragraph("Photo Evidence", h2))
        for url in event.evidence_photos:
            local_path = os.path.join(settings.MEDIA_ROOT, url.split("/media/")[-1])
            if os.path.exists(local_path):
                try:
                    story.append(RLImage(local_path, width=3 * inch, height=2.2 * inch))
                    story.append(Spacer(1, 8))
                except Exception:
                    story.append(Paragraph(url, styles["Normal"]))
            else:
                story.append(Paragraph(url, styles["Normal"]))
        story.append(Spacer(1, 8))

    if event.evidence_clips:
        story.append(Paragraph("Audio Evidence (download links)", h2))
        for url in event.evidence_clips:
            story.append(Paragraph(f'<link href="{url}">{url}</link>', styles["Normal"]))
        story.append(Spacer(1, 8))

    if event.evidence_videos:
        story.append(Paragraph("Video Evidence (download links)", h2))
        for url in event.evidence_videos:
            story.append(Paragraph(f'<link href="{url}">{url}</link>', styles["Normal"]))
        story.append(Spacer(1, 8))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    buffer.seek(0)
    return StreamingResponse(
        buffer, media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="safeher-report-{event.id}.pdf"'},
    )
